<?php

namespace App\Enums\Appointment;

enum MotiveEnum: int
{
    case MODEL_REJECT_LAB_EXTERNAL = 1;
    case MODEL_COAGULATED = 2;
    case MODEL_COLLECTED_ANTI_INCORRECT = 3;
    case MODEL_CONTAMINED = 4;
    case MODEL_LOST = 5;
    case MODEL_HEMOLYZED = 6;
    case MODEL_ICTERICA = 7;
    case MODEL_IDENTITY_INCORRECT = 8;
    case MODEL_INADEQUATE = 9;
    case MODEL_INSUFFICIENT = 10;
    case MODEL_LIPEMICA = 11;
    case MODEL_BAN_CONDITION = 12;
    case MODEL_NOT_HARVESTED = 13;
    case MODEL_REJECTED = 14;
    case DELAY_READ = 15;
    case CENTRIFUGATION_INADEQUATE = 16;
    case COLLECT_INADEQUATE_MODEL = 17;
    case COLLECTOR_INADEQUATE = 18;
    case EXAM_REGISTERED_WITH_ERROR = 19;
    case EXAM_COLELCT_UNREALIZED = 20;
    case EXAM_WITHOUT_RESULT = 21;
    case EXAM_UNREALIZED = 22;
    case EXAM_REGISTERED_INCORRECT = 23;
    case NEW_MODEL_CONFIRM_RESULT = 24;
    case NEW_MODEL_ACCIDENT = 25;
    case RECOLET = 26;
    case RELATION_REGISTER_INCORRECT = 27;
    case EXCHANGE_MATERIAL = 28;

    public function getName(): string
    {
        return match($this) {
            static::MODEL_REJECT_LAB_EXTERNAL => 'AMOSTA REJEITADA LABOR EXTERNO',
            static::MODEL_COAGULATED => 'AMOSTRA COAGULADA',
            static::MODEL_COLLECTED_ANTI_INCORRECT => 'AMOSTRA COLETADA EM ANTICOAGULANTE ERRADO',
            static::MODEL_CONTAMINED => 'AMOSTRA CONTAMINADA',
            static::MODEL_LOST => 'AMOSTRA EXTRAVIADA',
            static::MODEL_HEMOLYZED => 'AMOSTRA HEMOLISADA',
            static::MODEL_ICTERICA => 'AMOSTRA ICTERICA',
            static::MODEL_IDENTITY_INCORRECT => 'AMOSTRA IDENTIFICADA ERRADA',
            static::MODEL_INADEQUATE => 'AMOSTRA INADEQUADA',
            static::MODEL_INSUFFICIENT => 'AMOSTRA INSUFICIENTE',
            static::MODEL_LIPEMICA => 'AMOSTRA LIPÊMICA',
            static::MODEL_BAN_CONDITION => 'AMOSTRA MAL ACONDICIONADA',
            static::MODEL_NOT_HARVESTED => 'AMOSTRA NAO COLHIDA',
            static::MODEL_REJECTED => 'AMOSTRA REJEITADA',
            static::DELAY_READ => 'ATRASO NA LEITURA DE INTRADERMORREACOES',
            static::CENTRIFUGATION_INADEQUATE => 'CENTRIFUGACAO INADEQUADA DE AMOSTRA',
            static::COLLECT_INADEQUATE_MODEL => 'COLETA INADEQUADA DA AMOSTRA',
            static::COLLECTOR_INADEQUATE => 'COLETOR INADEQUADO PARA A AMOSTRA',
            static::EXAM_REGISTERED_WITH_ERROR => 'EXAME CADASTRADO ERRADO',
            static::EXAM_COLELCT_UNREALIZED => 'EXAME DE COLETA NAO FOI REALIZADO',
            static::EXAM_WITHOUT_RESULT => 'EXAME DE COLETA NAO TEVE O RESULTADO REGISTRADO',
            static::EXAM_UNREALIZED => 'EXAME NAO REALIZADO',
            static::EXAM_REGISTERED_INCORRECT => 'EXAME REALIZADO NA COLETA REGISTRADO INCORRETAMENTE',
            static::NEW_MODEL_CONFIRM_RESULT => 'NOVA AMOSTRA PARA CONFIRMACAO DE RESULTADO',
            static::NEW_MODEL_ACCIDENT => 'NOVA AMOSTRA POR ACIDENTE',
            static::RECOLET => 'RECOLETA',
            static::RELATION_REGISTER_INCORRECT => 'RELACIONADO A CADASTRO INCORRETO',
            static::EXCHANGE_MATERIAL => 'TROCA DE MATERIAL DE AMOSTRA',
        };
    }

}
